name: Prepare Release Tag

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  build:
    name: Prepare Release Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set Version
        run: ./scripts/set-version.sh ${{ github.ref_name }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: "v.${{ github.ref_name }}"
          message: "Release version: ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
