name: Prepare Release Tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Prepare Release Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Set Version
        run: ./scripts/set-version.sh ${{ github.ref_name }}

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ github.ref_name }}"
          tag_exists_error: false
          message: "Release version: ${{ github.ref_name }}"
          token: ${{ secrets.PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          force_push_tag: true
          message: "Release version: ${{ github.ref_name }}"
          token: ${{ secrets.PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
