name: Prepare Release Tag

on:
  push:
    tags:
      - "prep-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Prepare Release Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Split version
        id: split_version
        run: |
          export plain_tag=$(TAG_NAME=${{ github.ref_name }}; echo "$TAG_NAME" | cut -d "-" -f 2)
          echo "version=${plain_tag}" >> $GITHUB_OUTPUT    

      - name: Set version
        run: ./scripts/set-version.sh ${{ steps.split_version.outputs.version }}

      - name: Commit new version
        id: auto_commit_action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git_cliff
        with:
          config: cliff.toml
          args: latest..v${{ steps.auto_commit_action.outputs.commit_hash }} --tag v${{ steps.split_version.outputs.version }}

      - name: Create release tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.split_version.outputs.version }}"
          tag_exists_error: false
          message: "${{ steps.git_cliff.outputs.content }}"
          github_token: ${{ secrets.PAT }}
          commit_sha: ${{ steps.auto_commit_action.outputs.commit_hash }}

      - name: Recreate latest tag
        uses: rickstaa/action-create-tag@v1
        id: "re_tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          force_push_tag: true
          message: "${{ steps.git_cliff.outputs.content }}"
          github_token: ${{ secrets.PAT }}
          commit_sha: ${{ steps.auto_commit_action.outputs.commit_hash }}
